openapi: 3.0.0
info:
  title: Summative Assessment Spring Boot and REST
  description: A simple web service that provides quote-of-the-day, word-of-the-day, and magic 8-ball service.
  version: 0.0.1
servers: 
    - url: http://localhost:8080
      description: Local dev server
      
paths:
  /quote/:
    get:
      summary: provides quote of a day.
      description: A simple service that provides quote of a day.
      